export const SEO_KEYWORDS: string[] = [
  // Brand specific keywords
  "poésie coffee",
  "poésie coffee paris",
  "poésie coffee bastille",
  "poésie coffee 11ème",
  "poésie coffee 11th",
  "poésie coffee workshop",
  "poésie coffee atelier",
  "poésie coffee café",
  "poésie coffee tea",
  "poésie coffee thé",
  // Quality and experience keywords
  "meilleur café paris",
  "best coffee shop paris",
  "top café paris",
  "café de spécialité paris",
  "specialty coffee paris",
  "coffee roaster paris",
  "torréfacteur paris",
  "café artisanal paris",
  "coffee tasting paris",
  "dégustation café paris",
  "coffee experience paris",
  "café cosy paris",
  "café authentique paris",
  "café indépendant paris",
  // French keywords
  "café paris",
  "thé paris",
  "ateliers paris",
  "café boutique",
  "café culturel",
  "workshop paris",
  "café artisanal",
  "thé artisanal",
  // Location specific keywords
  "café paris 11",
  "café 11ème arrondissement",
  "café bastille",
  "café près de bastille",
  "café 11ème paris",
  "thé 11ème arrondissement",
  "ateliers bastille",
  "workshop 11ème arrondissement",
  // English keywords for international visibility
  "coffee paris",
  "tea paris",
  "workshops paris",
  "coffee shop paris",
  "cultural café paris",
  "paris workshops",
  "artisan coffee paris",
  "artisan tea paris",
  "best coffee paris",
  "best tea paris",
  "coffee workshop paris",
  "tea workshop paris",
  "paris coffee shop",
  "paris tea house",
  "independent coffee shop paris",
  "authentic coffee shop paris",
  "specialty coffee shop paris",
  // Location specific English keywords
  "coffee paris 11th",
  "coffee 11th arrondissement",
  "coffee bastille",
  "coffee near bastille",
  "tea 11th arrondissement",
  "workshops bastille",
  "coffee shop bastille",
  "tea house bastille",
];
