export const SEO_KEYWORDS: string[] = [
  // Brand specific keywords
  "poésie coffee",
  "poésie coffee paris",
  "poésie coffee bastille",
  "poésie coffee 11ème",
  "poésie coffee 11th",
  "poésie coffee workshop",
  "poésie coffee atelier",
  "poésie coffee café",
  "poésie coffee tea",
  "poésie coffee thé",
  // Quality and experience keywords
  "meilleur café paris",
  "best coffee shop paris",
  "top café paris",
  "café de spécialité paris",
  "specialty coffee paris",
  "coffee roaster paris",
  "torréfacteur paris",
  "café artisanal paris",
  "coffee tasting paris",
  "dégustation café paris",
  "coffee experience paris",
  "café cosy paris",
  "café authentique paris",
  "café indépendant paris",
  // Dog friendly keywords
  "café dog friendly paris",
  "coffee shop dog friendly paris",
  "café accepte chiens paris",
  "coffee shop accepts dogs paris",
  "café avec chiens paris",
  "dog friendly café paris",
  "café pour chiens paris",
  "coffee shop with dogs paris",
  "café où emmener son chien paris",
  "dog friendly coffee paris",
  // Kid friendly keywords
  "café kid friendly paris",
  "coffee shop kid friendly paris",
  "café enfants paris",
  "coffee shop children paris",
  "café famille paris",
  "family friendly café paris",
  "café avec enfants paris",
  "coffee shop with kids paris",
  "café adapté enfants paris",
  "child friendly coffee paris",
  "café pour famille paris",
  "family coffee shop paris",
  // Coworking keywords
  "café coworking paris",
  "coffee shop coworking paris",
  "café télétravail paris",
  "coffee shop remote work paris",
  "café bureau paris",
  "coffee shop office paris",
  "café travail paris",
  "coffee shop work paris",
  "café wifi paris",
  "coffee shop wifi paris",
  "café espace travail paris",
  "coffee shop workspace paris",
  "café ordinateur paris",
  "coffee shop laptop paris",
  "café étudiant paris",
  "coffee shop student paris",
  // French keywords
  "café paris",
  "thé paris",
  "ateliers paris",
  "café boutique",
  "café culturel",
  "workshop paris",
  "café artisanal",
  "thé artisanal",
  // Location specific keywords
  "café paris 11",
  "café 11ème arrondissement",
  "café bastille",
  "café près de bastille",
  "café 11ème paris",
  "thé 11ème arrondissement",
  "ateliers bastille",
  "workshop 11ème arrondissement",
  // English keywords for international visibility
  "coffee paris",
  "tea paris",
  "workshops paris",
  "coffee shop paris",
  "cultural café paris",
  "paris workshops",
  "artisan coffee paris",
  "artisan tea paris",
  "best coffee paris",
  "best tea paris",
  "coffee workshop paris",
  "tea workshop paris",
  "paris coffee shop",
  "paris tea house",
  "independent coffee shop paris",
  "authentic coffee shop paris",
  "specialty coffee shop paris",
  // Location specific English keywords
  "coffee paris 11th",
  "coffee 11th arrondissement",
  "coffee bastille",
  "coffee near bastille",
  "tea 11th arrondissement",
  "workshops bastille",
  "coffee shop bastille",
  "tea house bastille",
];
